const os=require('node:os')
console.log("Informacion del Sistema Operativo")
console.log("---------------")
console.log("Nombre SO:",os.platform())
console.log("Version SO:",os.release())
console.log("Aquitectura SO:",os.arch())
console.log("CPU's SO:",os.cpus())
console.log("Memoria libre SO:",os.freemem()/1024/1024)
console.log("Memoria total SO:",os.totalmem()/1024/1024)
console.log("Uptime SO:",os.uptime()/60/60)