const os=require('node:os')
console.log("Informacion del Sistema Operativo")
console.log("==========================")
console.log("Nombre SO:",os.platform())
console.log("Version SO:",os.release())
console.log("Arquitectura SO:",os.arch())
console.log("CPUS SO:",os.cpus())
console.log("Memroria libre SO:",os.freemem()/1024/1024)
console.log("Memroria total SO:",os.totalmem()/1024/1024)
console.log("uptime SO:",os.uptime())