const os=require('node:os')
console.log("informcion del sistema operativo") 
console.log("------------------------") 
console.log("nombre SO:",os.platform()) 
console.log("version SO:",os.release()) 
console.log("arquitectura SO:",os.arch()) 
console.log("CPUs SO:",os.cpus()) 
console.log("memoria libre SO:",os.freemem()/1024/1024) 
console.log("memoria total SO:",os.totalmem()/1024/1024) 
console.log("uptime SO:",os.uptime()/60/60) 